### ISSUE TITLE
Wrong api address for 'Check for compatible module binary to download?'

### ISSUE THREAD

**Issue by dalanicolai** [dzop/emacs-zmq#23]
Because the repository has moved the api-call to look for binaries is broken.

Using the old api address with curl:
```
curl   -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/dzop/emacs-zmq/releases/v0.10.10

{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/133400325/releases/v0.10.10",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```
With the new address:
```
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/nnicandro/emacs-zmq/releases/v0.10.10

{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release"
}
```

**Comment by nnicandro** [comment]
Thanks, I fixed it.

**Comment by dalanicolai** [comment]
Great!

**Comment by dalanicolai** [comment]
It seems like this is not yet fixed. You should look more carefully to the curl commands that I wrote in the original issue. It looks like just changing the 'dzop' to 'nnicandro' in the URL does not fix it.
